package com.wheelshiftpro.dto.response;

import com.wheelshiftpro.enums.CoolingSystem;
import com.wheelshiftpro.enums.MotorcycleStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * DTO for motorcycle response.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MotorcycleResponse {

    private Long id;
    private String vinNumber;
    private String registrationNumber;
    private String engineNumber;
    private String chassisNumber;
    
    // Motorcycle Model Info (flattened)
    private Long motorcycleModelId;
    private String motorcycleModelFullName;
    private String make;
    private String model;
    private String variant;
    private Integer modelYear;
    
    private String color;
    private Integer mileageKm;
    private Integer manufactureYear;
    private LocalDate registrationDate;
    private MotorcycleStatus status;
    
    // Storage Location (flattened)
    private Long storageLocationId;
    private String storageLocationName;
    
    private BigDecimal purchasePrice;
    private LocalDate purchaseDate;
    private BigDecimal sellingPrice;
    private BigDecimal minimumPrice;
    private Integer previousOwners;
    private LocalDate insuranceExpiryDate;
    private LocalDate pollutionCertificateExpiry;
    private Boolean isFinanced;
    private Boolean isAccidental;
    private String description;
    
    // File IDs (for reference)
    private String primaryImageId;
    private String galleryImageIds;
    private String documentFileIds;

    // File URLs (generated by mapper)
    private String primaryImageUrl;
    private List<String> galleryImageUrls;
    private List<String> documentFileUrls;
    
    // Detailed Specs (merged from MotorcycleDetailedSpecsResponse)
    // Engine Specifications
    private String engineType;
    private BigDecimal maxPowerBhp;
    private BigDecimal maxTorqueNm;
    private CoolingSystem coolingSystem;
    private BigDecimal fuelTankCapacity;
    private BigDecimal claimedMileageKmpl;
    
    // Dimensions
    private Integer lengthMm;
    private Integer widthMm;
    private Integer heightMm;
    private Integer wheelbaseMm;
    private Integer groundClearanceMm;
    private Integer kerbWeightKg;
    
    // Braking System
    private String frontBrakeType;
    private String rearBrakeType;
    private Boolean absAvailable;
    
    // Suspension
    private String frontSuspension;
    private String rearSuspension;
    
    // Tires
    private String frontTyreSize;
    private String rearTyreSize;
    
    // Features
    private Boolean hasElectricStart;
    private Boolean hasKickStart;
    private Boolean hasDigitalConsole;
    private Boolean hasUsbCharging;
    private Boolean hasLedLights;
    private String additionalFeatures;
    
    // Computed fields
    private BigDecimal profitMargin;
    private BigDecimal powerToWeightRatio;
    private Integer ageInYears;
    private Boolean isInsuranceExpired;
    private Boolean isPollutionCertificateExpired;
    private String fullIdentification;
    
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
