-- V17__Seed_Motorcycle_Models.sql
-- 1. Drops seating_capacity column (field removed from entity)
-- 2. Seeds motorcycle model catalog from bikes-dataset.csv
--    Columns: make, model, variant(null), year(2022), engine_capacity, fuel_type, transmission_type, vehicle_type, is_active

-- ============================================================
-- STEP 1: Drop seating_capacity column
-- ============================================================
ALTER TABLE motorcycle_models DROP COLUMN seating_capacity;

-- ============================================================
-- STEP 2: Seed motorcycle models
-- ============================================================
INSERT IGNORE INTO motorcycle_models (make, model, variant, year, engine_capacity, fuel_type, transmission_type, vehicle_type, is_active) VALUES  ('Gravton Motors', 'Quanta', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Simple Energy', 'One', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okaya', 'Classiq', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Oben Electric', 'Rorr', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ola Electric', 'S1', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ola Electric', 'S1 Pro', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Revolt', 'RV300', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okinawa', 'Praise', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero Electric', 'NYX HX', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Crayon Motors', 'Envy', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('22Kymco', 'Flow', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okinawa', 'Okhi 90', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Revolt', 'RV400', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Kabira Mobility', 'KM 4000', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('One Moto', 'Electa', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Odysse', 'Evoqis', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okinawa', 'i-Praise', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Li-ions Elektrik', 'Spock', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Tork Motors', 'Kratos', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Kabira Mobility', 'KM 3000', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('EeVe', 'Soul', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('BGauss', 'D15', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Nexzu Mobility', 'Dextro', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('BGauss', 'A2', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Nexzu Mobility', 'Dextro +', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero Electric', 'Photon HX', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Bajaj', 'CT 110', NULL, 2022, 115, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Atumobile', 'Atum 1.0', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okinawa', 'Ridge +', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Boom Motors', 'Corbett-14', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Earth Energy EV', 'Glyde +', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ather', '450', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Bajaj', 'Platina 100', NULL, 2022, 102, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Chetak', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Bajaj', 'CT 100', NULL, 2022, 102, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'HF Deluxe i3s', NULL, 2022, 97, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Star City +', NULL, 2022, 110, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero Electric', 'Flash LX', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero Electric', 'Atria LX', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ampere', 'Zeal Ex', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero', 'Passion Pro i3S', NULL, 2022, 113, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bounce', 'Infinity E1', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero', 'HF Deluxe', NULL, 2022, 97, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero Electric', 'Optima HX', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Polarity', 'Executive', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Polarity', 'Sport', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Bajaj', 'Platina 110', NULL, 2022, 115, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Gemopai', 'Astrid Lite', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Kawasaki', 'KLX 110', NULL, 2022, 112, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('TVS', 'Sport', NULL, 2022, 110, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'Splendor iSmart', NULL, 2022, 113, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Odysse', 'V2', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ampere', 'Magnus Pro', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('TVS', 'iQube', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Honda', 'CD 110 Dream', NULL, 2022, 110, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'Livo', NULL, 2022, 110, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Victor', NULL, 2022, 110, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'HF 100', NULL, 2022, 97, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Odysse', 'Racer', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('BGauss', 'B8', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero', 'Splendor +', NULL, 2022, 97, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ampere', 'Zeal', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('TVS', 'Radeon', NULL, 2022, 110, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'Pleasure + 110', NULL, 2022, 111, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('TVS', 'XL 100', NULL, 2022, 100, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Raider', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'Fascino 125', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Yamaha', 'Ray-ZR 125FI', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Hero', 'Splendor Pro', NULL, 2022, 97, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Scooty Pep +', NULL, 2022, 88, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Hero', 'Maestro Edge', NULL, 2022, 111, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Honda', 'CB Shine', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'SP 125', NULL, 2022, 124, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Pulsar 150', NULL, 2022, 150, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'New Access 125', NULL, 2022, 124, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Suzuki', 'Gixxer', NULL, 2022, 155, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Scooty Zest 110', NULL, 2022, 110, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('TVS', 'Jupiter', NULL, 2022, 110, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Bajaj', 'Pulsar 125', NULL, 2022, 124, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CB Unicorn 160', NULL, 2022, 163, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Lohia', 'Omastar', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okinawa', 'R30', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Okinawa', 'Dual', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Hero', 'Super Splendor', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'Glamour 125', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Ntorq 125', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Kawasaki', 'KLX 140G', NULL, 2022, 144, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Evolet', 'Pony', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Evolet', 'Polo', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Evolet', 'Derby', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ampere', 'Reo Elite', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Honda', 'Dio', NULL, 2022, 110, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Suzuki', 'Avenis', NULL, 2022, 124, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Hero', 'Xtreme 160R', NULL, 2022, 163, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'KX 100', NULL, 2022, 99, 'PETROL', 'MANUAL', 'DIRT_BIKE', TRUE),
  ('Hero', 'Destini 125', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Honda', 'Grazia', NULL, 2022, 124, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Suzuki', 'Burgman', NULL, 2022, 124, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Okinawa', 'Lite', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('TVS', 'Jupiter 125', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Bajaj', 'Pulsar NS 125', NULL, 2022, 124, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'Maestro Edge 125', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('TVS', 'Apache RTR 160', NULL, 2022, 160, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'MT-15', NULL, 2022, 155, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'MT-15 V2.0', NULL, 2022, 155, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Apache RTR 180', NULL, 2022, 177, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'Gixxer SF', NULL, 2022, 155, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'R15S V3.0', NULL, 2022, 155, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Ampere', 'V48', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ampere', 'Reo', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Ampere', 'Magnus', NULL, 2022, NULL, 'ELECTRIC', 'AUTOMATIC', 'SCOOTER', TRUE),
  ('Honda', 'Activa 6G', NULL, 2022, 110, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Honda', 'Activa 125 FI', NULL, 2022, 124, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Piaggio', 'Vespa', NULL, 2022, 125, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Yamaha', 'FZ V3.0 FI', NULL, 2022, 149, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Avenger Street 160', NULL, 2022, 160, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Bajaj', 'Avenger Street 220', NULL, 2022, 220, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Bajaj', 'Pulsar 180', NULL, 2022, 179, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Pulsar NS160', NULL, 2022, 160, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'X-Blade', NULL, 2022, 163, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'FZ S V3.0 FI', NULL, 2022, 149, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'FZ-X', NULL, 2022, 149, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Piaggio', 'Vespa 150', NULL, 2022, 155, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('Royal Enfield', 'Bullet 350', NULL, 2022, 346, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Yamaha', 'Aerox 155', NULL, 2022, 155, 'PETROL', 'CVT', 'SCOOTER', TRUE),
  ('TVS', 'Apache RTR 165 RP', NULL, 2022, 165, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'YZF R15 V4.0', NULL, 2022, 155, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Royal Enfield', 'Himalayan', NULL, 2022, 411, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Suzuki', 'Intruder', NULL, 2022, 155, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Hero', 'XPulse 200T', NULL, 2022, 200, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Yamaha', 'FZ 25', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'FZS 25', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'Fazer 25', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'XPulse 200', NULL, 2022, 200, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('TVS', 'Apache RTR 200 FI E100', NULL, 2022, 198, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'H Ness CB 350', NULL, 2022, 348, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Royal Enfield', 'Meteor 350', NULL, 2022, 349, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('KTM', 'RC 125', NULL, 2022, 125, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Aprilia', 'SR 150', NULL, 2022, 155, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Aprilia', 'Storm 125', NULL, 2022, 124, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Aprilia', 'SR 125', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Aprilia', 'SXR 125', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Avenger Cruise 220', NULL, 2022, 220, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Bajaj', 'Pulsar 220', NULL, 2022, 220, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'XPulse 200 4V', NULL, 2022, 200, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Honda', 'Hornet 2.0', NULL, 2022, 184, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Pulsar F250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CB200X', NULL, 2022, 184, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'Gixxer SF 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'Gixxer 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('JAWA', 'Forty Two', NULL, 2022, 293, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('JAWA', '300', NULL, 2022, 293, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Royal Enfield', 'Classic 350', NULL, 2022, 349, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('JAWA', '42', NULL, 2022, 293, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Benelli', 'Leoncino 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Hero', 'Xtreme 200S', NULL, 2022, 200, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Aprilia', 'SR 160', NULL, 2022, 160, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Aprilia', 'SXR 160', NULL, 2022, 160, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Pulsar 200 NS', NULL, 2022, 200, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Pulsar N250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Pulsar RS 200', NULL, 2022, 200, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Bajaj', 'Dominar 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('KTM', '200 Duke', NULL, 2022, 200, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CB 350 RS', NULL, 2022, 348, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('JAWA', 'Perak', NULL, 2022, 334, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('KTM', 'RC 200', NULL, 2022, 200, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Husqvarna', 'Vitpilen 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Husqvarna', 'Svartpilen 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('KTM', '250 Adventure', NULL, 2022, 248, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('KTM', '390 Duke', NULL, 2022, 373, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('KTM', 'RC 390', NULL, 2022, 373, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('KTM', '125 Duke', NULL, 2022, 125, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Cleveland Cyclewerks', 'Ace Deluxe', NULL, 2022, 229, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'V-Strom SX 250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('CFMoto', '300NK', NULL, 2022, 292, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Apache RTR 200 4V', NULL, 2022, 198, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Benelli', 'Imperiale 400', NULL, 2022, 374, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Benelli', 'TRK 502', NULL, 2022, 500, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Honda', 'CB300R', NULL, 2022, 286, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Apache RTR 160 4V', NULL, 2022, 160, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'R15 V3.0', NULL, 2022, 155, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Yezdi', 'Roadster', NULL, 2022, 334, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Royal Enfield', 'Scram 411', NULL, 2022, 411, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Yezdi', 'Scrambler', NULL, 2022, 334, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yezdi', 'Adventure', NULL, 2022, 334, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('KTM', '250 Duke', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Cleveland Cyclewerks', 'Misfit', NULL, 2022, 229, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'G 310 R', NULL, 2022, 313, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('TVS', 'Apache RR 310', NULL, 2022, 312, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('BMW', 'G 310 GS', NULL, 2022, 313, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Honda', 'CB500X', NULL, 2022, 471, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', 'C 400 GT', NULL, 2022, 350, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Royal Enfield', 'Classic Chrome', NULL, 2022, 499, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Bajaj', 'Dominar 400 [2019]', NULL, 2022, 373, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Triumph', 'Bonneville T100', NULL, 2022, 900, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Kawasaki', 'Z250', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja 300', NULL, 2022, 296, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('FB Mondial', 'HPS 300', NULL, 2022, 249, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Royal Enfield', 'Interceptor 650', NULL, 2022, 648, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Royal Enfield', 'Continental GT 650', NULL, 2022, 648, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Triumph', 'Trident 660', NULL, 2022, 660, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'V-Strom 650XT', NULL, 2022, 645, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Mahindra', 'Mojo', NULL, 2022, 295, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('KTM', '390 Adventure', NULL, 2022, 373, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Kawasaki', 'Ninja 400', NULL, 2022, 399, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Kawasaki', 'KX250F', NULL, 2022, 249, 'PETROL', 'MANUAL', 'DIRT_BIKE', TRUE),
  ('Kawasaki', 'KX 450', NULL, 2022, 449, 'PETROL', 'MANUAL', 'DIRT_BIKE', TRUE),
  ('Honda', 'CB 650 R', NULL, 2022, 649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CBR650R', NULL, 2022, 649, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Indian', 'Scout Sixty', NULL, 2022, 999, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Indian', 'Scout', NULL, 2022, 1131, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Benelli', 'TRK 251', NULL, 2022, 249, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Benelli', 'Leoncino', NULL, 2022, 500, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'F900R', NULL, 2022, 895, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', '1200 Custom', NULL, 2022, 1202, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Tiger 850 Sport', NULL, 2022, 888, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Triumph', 'Bonneville Bobber', NULL, 2022, 1200, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('BMW', 'F900XR', NULL, 2022, 895, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Multistrada 1200 Enduro', NULL, 2022, 1198, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja ZX-6R', NULL, 2022, 636, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Triumph', 'Speedmaster', NULL, 2022, 1200, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Kawasaki', 'Z650RS', NULL, 2022, 649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Vulcan S', NULL, 2022, 649, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Kawasaki', 'KLX 450R', NULL, 2022, 449, 'PETROL', 'MANUAL', 'DIRT_BIKE', TRUE),
  ('KTM', '790 Duke', NULL, 2022, 799, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Versys X-300', NULL, 2022, 296, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Triumph', 'Tiger Sport 660', NULL, 2022, 660, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', '750 GS', NULL, 2022, 853, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', '850 GS', NULL, 2022, 853, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Triumph', 'Speed Triple 1200 RS', NULL, 2022, 1160, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R nine T', NULL, 2022, 1170, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('CFMoto', '650NK', NULL, 2022, 649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja 650', NULL, 2022, 649, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Triumph', 'Thruxton R', NULL, 2022, 1200, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('BMW', 'R 1250 R', NULL, 2022, 1254, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'S 1000 R', NULL, 2022, 999, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('BMW', 'R 1250 GS', NULL, 2022, 1254, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', 'R 1250 GS Adventure', NULL, 2022, 1254, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', 'R 1250 RT', NULL, 2022, 1254, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Speed Twin', NULL, 2022, 1200, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Triumph', 'Scrambler 1200', NULL, 2022, 1200, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Aprilia', 'Tuono 660', NULL, 2022, 659, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Aprilia', 'RS 660', NULL, 2022, 659, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Moto Guzzi', 'V85 TT', NULL, 2022, 853, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CRF1100L Africa Twin', NULL, 2022, 1084, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Benelli', 'BN 302R', NULL, 2022, 300, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Benelli', '502C', NULL, 2022, 500, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('CFMoto', '650MT', NULL, 2022, 649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('CFMoto', '650GT', NULL, 2022, 649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Versys 650', NULL, 2022, 649, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Ducati', 'Scrambler', NULL, 2022, 803, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Iron 883', NULL, 2022, 883, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Scrambler Desert Sled', NULL, 2022, 803, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Forty-Eight', NULL, 2022, 1202, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Roadster', NULL, 2022, 1202, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Ducati', 'Hypermotard', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Hyperstrada', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'SuperSport', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R 1200 R', NULL, 2022, 1170, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R 1200 RS', NULL, 2022, 1170, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Z900RS', NULL, 2022, 948, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R nineT Scrambler', NULL, 2022, 1197, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R 1200 GS Adventure', NULL, 2022, 1170, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', 'R 1200 RT', NULL, 2022, 1170, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'YZF R1', NULL, 2022, 998, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Indian', 'Chief Dark Horse', NULL, 2022, 1890, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Chief Classic', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'S 1000 XR', NULL, 2022, 999, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Chief Bobber Dark Horse', NULL, 2022, 1890, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Indian', 'Chief Vintage', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Chieftain', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Scrambler 1100', NULL, 2022, 1079, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Multistrada 1260', NULL, 2022, 1262, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Street Triple', NULL, 2022, 765, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Benelli', 'TNT 600i', NULL, 2022, 600, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Yamaha', 'MT-09', NULL, 2022, 847, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Avantura', 'Choppers Rudra', NULL, 2022, 2026, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Monster 797', NULL, 2022, 803, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Monster', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Diavel 1260', NULL, 2022, 1262, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Z650', NULL, 2022, 649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Street Twin', NULL, 2022, 900, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Street Scrambler', NULL, 2022, 900, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Bonneville T120', NULL, 2022, 1200, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Honda', 'CB1000R +', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', '959 Panigale', NULL, 2022, 955, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Moto Guzzi', 'V9 Roamer', NULL, 2022, 850, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Moto Guzzi', 'V9 Bobber', NULL, 2022, 850, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Ducati', 'Multistrada 1200', NULL, 2022, 1198, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R 1200', NULL, 2022, 1170, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'FTR 1200', NULL, 2022, 1203, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CBR 1000RR', NULL, 2022, 999, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Harley-Davidson', 'Pan America 1250', NULL, 2022, 1252, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('MV', 'Agusta Brutale 800', NULL, 2022, 798, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Tiger 1200', NULL, 2022, 1160, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Kawasaki', 'Ninja ZX-14R', NULL, 2022, 1441, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('MV', 'Agusta Brutale 800 RR', NULL, 2022, 798, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Avantura', 'Choppers Pravega', NULL, 2022, 2026, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Chieftain Dark Horse', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Chieftain Elite', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'R 18', NULL, 2022, 1802, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja 1000', NULL, 2022, 1043, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Tiger 900', NULL, 2022, 888, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('BMW', 'S 1000 RR', NULL, 2022, 999, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('MV', 'Agusta Turismo Veloce 800', NULL, 2022, 798, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Road King', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'CRF1000L Africa Twin', NULL, 2022, 999, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Ducati', 'Multistrada V2', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Multistrada 950', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Panigale V2', NULL, 2022, 955, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'M 1000 RR', NULL, 2022, 999, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Z900', NULL, 2022, 948, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Street Bob', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Softail Low Rider', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Fat Bob', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Z1000', NULL, 2022, 1043, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja ZX-10R', NULL, 2022, 998, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Kawasaki', 'Z1000R', NULL, 2022, 1043, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'XDiavel', NULL, 2022, 1262, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja ZX-10RR', NULL, 2022, 998, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('Harley-Davidson', 'Fat Boy', NULL, 2022, 1868, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Softail Deluxe', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Heritage Softail Classic', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Monster 1200', NULL, 2022, 1198, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('MV', 'Agusta Brutale 1090', NULL, 2022, 1078, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Z H2', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja H2 SX', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Moto Guzzi', 'Audace', NULL, 2022, 1380, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'K 1600 B', NULL, 2022, 1649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja H2 SX SE', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'K 1600', NULL, 2022, 1649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Moto Guzzi', 'MGX-21', NULL, 2022, 1380, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Street Glide Special', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Road Glide Special', NULL, 2022, 1745, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja H2', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('MV', 'Agusta F4 RR', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Roadmaster', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Roadmaster Elite', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', '1299 Panigale', NULL, 2022, 1285, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Ninja H2R', NULL, 2022, 998, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('MV', 'Agusta Dragster 800 RR', NULL, 2022, 798, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Panigale V4', NULL, 2022, 1103, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Multistrada V4', NULL, 2022, 1158, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'W800 Street', NULL, 2022, 773, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Kawasaki', 'Versys 1000', NULL, 2022, 1043, 'PETROL', 'MANUAL', 'OFF_ROAD', TRUE),
  ('Indian', 'Scout Bobber', NULL, 2022, 1133, 'PETROL', 'MANUAL', 'CRUISER', TRUE),
  ('Aprilia', 'Tuono V4', NULL, 2022, 1077, 'PETROL', 'MANUAL', 'SPORT_BIKE', TRUE),
  ('MV', 'Agusta F3 800 RC', NULL, 2022, 798, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Super Chief Limited', NULL, 2022, 1890, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Moto Guzzi', 'Eldorado', NULL, 2022, 1380, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Indian', 'Springfield', NULL, 2022, 1811, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Honda', 'Gold Wing', NULL, 2022, 1833, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'StreetFighter V4', NULL, 2022, 1103, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Monster 821', NULL, 2022, 821, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Triumph', 'Rocket 3', NULL, 2022, 2458, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('BMW', 'K 1600 GTL', NULL, 2022, 1649, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Aprilia', 'RSV4', NULL, 2022, 1099, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'Sportster S', NULL, 2022, 1252, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Suzuki', 'Hayabusa', NULL, 2022, 1340, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Ducati', 'Hypermotard 950', NULL, 2022, 937, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE),
  ('Harley-Davidson', 'CVO Limited', NULL, 2022, 1923, 'PETROL', 'MANUAL', 'MOTORCYCLE', TRUE);
